var zodiac_data =[
  {
    "zodiac": "",
    "h2_title": "Best-Suited Careers for Rats",
    "text": [
      "2020 is a year of the Rat, starting from January 25th, 2020 and lasting until February 11th, 2021. It will be a Gold Rat year. In 2021,a year of the Ox will follow.",
      "The Year of the Rat is the first zodiac sign in the Chinese zodiac cycle. According to the Chinese zodiac story, in the competition held by the Jade Emperor to decide the zodiac animals, the quick-witted rat asked the diligent ox to take him on a ride to cross the river and jumped down before the ox crossed the finish line, so the rat won the race and became the first of the zodiac animals.",
      "The 12 zodiac animals are, in order: Rat, Ox, Tiger, Rabbit, Dragon, Snake, Horse, Goat, Monkey, Rooster, Dog, and Pig. A Rat year occurs every 12 years.",
      "If you were born in 2008, 1996, 1984, 1972, 1960, 1948... you are a Rat.",
      "The Chinese zodiac year is usually said to start from Chinese New Year, which ranges from late January to mid February. ",
      "Therefore, if you were born in January or February in one of the above years, you might be a Rat, or possibly a Pig.",
      "You can use our \"Find Your Chinese Zodiac Sign\" tool to find your zodiac animal sign or see the table below.",
      "Choose your date of birth and find out about your Chinese zodiac sign.",
      "Rats are quick-witted, resourceful, versatile, kind, smart, and lovely.",
      "With strong intuition and quick responses, Rats always easily adapt themselves to a new environment. With rich imaginations and sharp observations, they can take advantage of various opportunities well.",
      "Rats have strong curiosity, so they tend to try their hands at anything, and they can deal with tasks skillfully.",
      "Ladies belonging to the Rat zodiac sign are pretty, smart, and lovely. They have quick minds and dexterous hands, and are able to learn anything.",
      "Due to a lack of courage, as well as good command skills, Rats are not capable of being leaders. Opportunistic and picky as Rats are, they do not have broad minds but take a narrow view of things.",
      "Chinese astrology states that certain zodiac animal combinations get along better than others, and that some animal signs are natural enemies.",
      "Chinese horoscope animals’ compatibility takes the characteristics of each animal into account.Those whose characteristics match well can have good compatibility.",
      "However, those who don't match need to put more effort into their relationships.",
      "The Rat and Ox have complementary characters and will help each other in their work and home lives.",
      "The Rat and Dragon will have a good relationship and support each other.",
      "Couples formed with a Rat and Rabbit will get along well and enjoy happiness.",
      "A Rat clasheseasily with a Horseora Rooster.They lack tolerancetoward each other and it’s hard to sustain a lasting peace.",
      "",
      "Take our online love Compatibility test.",
      "In Chinese element theory, each zodiac sign is associated with one of the five elements: Wood, Fire, Earth, Gold (Metal), and Water. For example, a Wood Rat comes once in a 60-year cycle.",
      "It is theorized that a person's characteristics are decided by their birth year's zodiac animal sign and element. So there are five types of Rat, each with different characteristics:",
      "See more about Chinese Zodiac Rats of 5 Elements: Characters and Destinies.",
      "With good insight and a sharp perspective, Rats have good judgment in what they do, which enables them to prevent unnecessary problems. Rats are cautious and meticulous, so they tend to show a serious attitude toward their work.",
      "The best careers for Rats are:",
      "Administrator, director, manager, entrepreneur, broadcaster, writer, musician, stand-up comedian, politician, lawyer, researcher, and racing car driver.",
      "General speaking, Rats are healthy. They are full of energy and active, which helps them keep fit and avoid illness.",
      "A balanced diet and regular exercise benefit Rats. With enough rest Rats can keep high spirits at work, which can improve work efficiency. When in stressful and tense conditions, Rats are suggested to take a tour to free stress and tension.",
      "With an active nature, Rats enjoy a flexible social circle. They are interested in attending different kinds of social occasions. They like to make new friends, but they seldom further their relationships with others. Rats have a charming appearance, which can attract more friends.",
      "In love relationships, Rats find it easy to start a new relationship with someone, but they also break off relationships easily, which results in trouble with infidelity.",
      " ",
      "In 2020, Rats are destined to experience a lot of challenges and ill fortune due to being in opposition to the Tai Sui star (or God of Age).",
      "Rats (those born in a Rat year) will now and then feel exhausted. However, the tough things will go their way if they control their mind properly and make efforts to align themselves with Tai Sui fengshui. Life will be easiest in the middle of the year.",
      "Read more on our Monthly Horoscope for Rats in 2020.",
      "According to Chinese astrology, the year of their birth sign (本命年běnmìngnián /bnn-ming-nyen/ 'origin (of) life year') will bring people nothing but bad luck. It is believed that people will offend Tai Sui, the God of Age, in their benmingnian.",
      "Therefore, Rats should pay special attention to avoid misfortune in their lives in the year of their birth sign. The next Rat year is 2020. It starts from Chinese New Year (January 25). Read more about How to Be Lucky in Your Ben Ming Nian."
    ]
  }
];